## Welcome to Python!!
a knowledge sharing session

references:
* https://github.com/jakevdp/PythonDataScienceHandbook
* http://tdc-www.harvard.edu/Python.pdf
* http://pandas.pydata.org/pandas-docs/stable/10min.html
* http://twiecki.github.io/blog/2014/11/18/python-for-data-science/
* https://www.dataquest.io/blog/machine-learning-python/
* with additional insights from various learning experiences

## Course Outline

* Installation
* Navigating the notebook
    * importing libraries
    * getting help
    * SYNTAX - the indentation, code structure
    * data types & basic operations
    * logical Operators
    * variable assignment
    > possible break here
    * Basic data structures - List, Dicts, Tuples, Strings
    * Basic lambda functions
    * saving notebook into a script file
    
* Data Manipulation with Pandas
    * Introduction to numpy arrays
    * broadcasting, reshaping
    * operations on np arrays
    * Introduction to pandas
    * getting and reading data
    * writing data
    * DataFrame manipulation 
        * https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf
        * creating DataFrame
        * subsetting DataFrame (Masking, iloc, loc)
        * summarizing data (df.describe,np.sum(), df.head etc)
        * adding columns to DataFrame (assign, df method)
    * Merging DataFrames
    
* Introduction to Statistical Analysis and Machine Learning
    * correlation
    * Statistical tests
    * Linear regression
    * Intro to scikit functions
    
* Assignment
    











### Importing libraries
in python, we import libraries using the following commands

In [2]:
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd

In [1]:
#this is how we comment
#below is how we find help
pd?
#help(pd.DataFrame)


Object `pd` not found.


### Basic python syntax
* Indentation instead of traditional {curly_braces} 
* Use \ when we should go the next line prematurely
* in function and class definitions, a colon usually appears
* index begins in zero

In [79]:
x = [1,2,3,4,5] #example of a list
y = [1,1,1,1,1]
z = []

for i in range(0,len(x)):
    z.append(x[i]+y[i])
    print(z[i],'index: %.i' %i)



2 index: 0
3 index: 1
4 index: 2
5 index: 3
6 index: 4


In [82]:
def adder(x,y):
    """ This a docstring for
    this adder function"""
    z = [] #initialize z
    for i in range(0,len(x)):
        z.append(x[i]+y[i])
        print(z)    
    return z
    
adder(x,y)
        

[2]
[2, 3]
[2, 3, 4]
[2, 3, 4, 5]
[2, 3, 4, 5, 6]


[2, 3, 4, 5, 6]

### Data types & basic operations


In [3]:
#integers
z = int(5/2)
print(z, type(z))

#float
pi = 3.141516
print(pi, type(pi))

txt = 'This is a string' #alternatively we can use ""
print(txt, type(txt))

#Complex Number
cmp = complex(3,7)
print(cmp, type(cmp))

2 <class 'int'>
3.141516 <class 'float'>
This is a string <class 'str'>
(3+7j) <class 'complex'>


In [4]:
a = 2+3 #addition
b = 3*5 #multiplication
c = 121/7 #division
d = 7%3 #modulo


In [12]:
for i in [a,b,c,d]:
    print(i)




5
15
17.285714285714285
1


### Logical Operators
in python, logical operators are words not symbols (and, or, not)

numerical comparisons are conventional

In [13]:
x = 5
y = 17
z = 9

In [19]:
print(x > y)
print(y < 5)
print(z == 9)
print(y != z)

False
False
True
True


In [20]:
(x < 8) or (y != 17) 

True

In [21]:
(x != 5) and (z > 9)

False

In [26]:
not( (x != 5) and (z > 9) )
#not gives the opposite

True

In [27]:
(x != 5) not (z > 9)

SyntaxError: invalid syntax (<ipython-input-27-7dfb3d79348d>, line 1)

### Variable Assignment
* In python, variable assignment create references not copies

In [83]:
x = 4 #assign 4 to x
y = x #assing x to y

In [87]:
x = 3 #change x to 3
y #print y

#note that y is changed too, y = x  did not create a copy of x to be assigned to y
#but why? :)
#try to search Garbage collection

3

In [88]:
# we can also do multiple assignments
x,y = 'this is x', 4
print(x)
print(y)

this is x
4


### Basic Data Structures
Lists, strings and tuples are ordered sequences of objects. Unlike strings that contain only characters, list and tuples can contain any type of objects. Lists and tuples are like arrays. Tuples like strings are immutables. Lists are mutables so they can be extended or reduced at will. Sets are mutable unordered sequence of unique elements whereas frozensets are immutable sets.


#### LISTS
* ordered sequence
* mutable
* can contain any type of objects

In [93]:
smpl = [1,2,3,4,5,6,7,8,91]
smpl
#Squares are defined by square brackets
#lists are mutable

[1, 2, 3, 4, 5, 6, 7, 8, 91]

In [94]:
smpl.pop(2) #here we pop the element at index 2, we can update a list!
smpl

[1, 2, 4, 5, 6, 7, 8, 91]

In [97]:
random = ['name', 100, True] #Lists can contain different types of object
random


['name', 100, True]

Problem 1: create a list of squared integers from 1 to 100

In [112]:

# sample of a list comprehension
#

#squared = [i**2 for i in range(0,100)]
#squared

#### TUPLES
* ordered sequence
* immutable
* can contain any type of objects

In [98]:
tupl = (1,2,3,4,5)
tupl

(1, 2, 3, 4, 5)

In [99]:
tupl.pop(3) #this will generate an error

AttributeError: 'tuple' object has no attribute 'pop'

#### STRINGS
* strings can be thought of as a list
* but they are immutable!

In [166]:
st = "Hello QBE!"
st[8]

'E'

### Indexing and Slicing
most of the time we need to index/filter our data

In [122]:
t = ["abc", 1 , np.exp(1), [100,8,4]]



Problem: How do we get the value 8?

In [123]:
# indexing by array notation
t[0]

4
3


In [130]:
# try negative!
t[-1]

#what's the difference?

[100, 8, 4]

In [124]:
#from index 1 up to before index 4
t[1:4]

[1, 2.7182818284590451, [100, 8, 4]]

In [126]:
#t[3][2]

In [138]:
#indexing by [start:stop:step]
num = [x for x in range(1,21)]
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [146]:
index1 = num[0:18:3]
index1


[1, 4, 7, 10, 13, 16]

**Question how can we reverse this list?**

### The 'in', '+', '*' operators

In [149]:
# in
#Say for example, we want to check if an element is in a list
a_list = [i**3 for i in range(0,100)]

In [151]:
729 in a_list

True

In [157]:
# +
#the + operatrs for lists is for concatenation
zoo = ['tiger', 'rooster', 'pig']
add_animal = ['snake', 'kangaroo']
current = zoo + add_animal


In [155]:
# *
#the * repeats the original content
"--Hello Manila "*3

'--Hello Manila --Hello Manila --Hello Manila '

**What if we want to replace a contents of a list?**

In [158]:
current

['tiger', 'rooster', 'pig', 'snake', 'kangaroo']

In [161]:
current[1] = 'monkey'

In [162]:
current

['tiger', 'monkey', 'pig', 'snake', 'kangaroo']

**I want to add catterpillar, how can I do it?**

In [164]:
current.append('catterpillar')
current

['tiger', 'monkey', 'pig', 'snake', 'kangaroo', 'catterpillar']

### DICTS (*dictionaries*)
dictionaries are set of key-value pairs, i.e a mapping
* objects of different types are ok
* keys : any immutable type
* values: anything
* items are key-value pairs
* defined by {curly braces}
* indexed by keys

In [168]:
d = {'tp1': 100, 'tp2': 200, 'tp3': 500, 'QBE': 4500}
d

{'QBE': 4500, 'tp1': 100, 'tp2': 200, 'tp3': 500}

**How can we build a mapping?**

In [177]:
person = ('A', 'B', 'C', 'D', 'E')
password = ('1234' , 'erZe', 'afsd', '1wh32')

In [185]:
my_dict = {} #initialize dict
for k,v in zip(person,password):
    my_dict[k] = v


In [186]:
my_dict
#what do you notice

{'A': '1234', 'B': 'erZe', 'C': 'afsd', 'D': '1wh32'}

In [189]:
#notice that the values are printed in no particular order
my_dict.keys()



dict_keys(['C', 'A', 'B', 'D'])

In [190]:
my_dict.values()

dict_values(['afsd', '1234', 'erZe', '1wh32'])

In [191]:
my_dict.items()

dict_items([('C', 'afsd'), ('A', '1234'), ('B', 'erZe'), ('D', '1wh32')])

In [193]:
#Indexing dicts
#dicts are indexed with keys
my_dict['F']
#notice the error! it's "KeyError" hahaha

KeyError: 'F'

### Lambda Functions
"a function has no name"
* lambda : arguments expression

In [196]:
#Lambda functions are anonymous functions, used only on the line they are called
def mult_list(x):
    for i in x:
        i*=i
    return(i)

In [197]:
s = [1,2,3,4,5,6]
result = mult_list(s)

36

In [205]:
#translate the above using a lambda function
result = lambda x: (x*2) ,s
result

(<function __main__.<lambda>>, [1, 2, 3, 4, 5, 6])

### Using If - Else 

In [212]:
def is_larger(x,num):
    if x > num:
        print('your fave number is larger than ', num)
    elif x < num:
        print('uhhhm this is lesser than your favorite', x)
    else:
        print('Just equal')

In [213]:
x = input("enter your favorite number: ")
num = input("Enter a random number: ")
is_larger(x,num)

enter your favorite number: 23
Enter a random number: 1
your fave number is larger than  1


**Now we want to save this file**

# Data Manipulation With Pandas
> we'll discuss some preliminaries

## Numpy Arrays
building blocks of Pandas and some more advanced libraries like tesorflow
> **So what's a numpy array?**
>> Cotains values of a single type, to see full list of available dtypes see: http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb


In [2]:
import numpy as np

n = np.array([12,3,4,5,6,7,8], dtype = 'float64')
n

#similar to a list

array([ 12.,   3.,   4.,   5.,   6.,   7.,   8.])

In [3]:
n.dtype

dtype('float64')

In [4]:
#numpy arrays can also be multidimensional arrays
np.random.seed(2)

x = np.random.randint(20, size = (3,4,5))
print(x.shape) #.ndim, .size
x

(3, 4, 5)


array([[[ 8, 15, 13,  8, 11],
        [18, 11,  8,  7,  2],
        [17, 11, 15,  5,  7],
        [ 3,  6,  4, 10, 11]],

       [[19,  7,  6, 10,  1],
        [ 3,  5,  4, 14,  6],
        [19,  2, 16, 14, 12],
        [18,  4, 15, 17,  7]],

       [[14,  8, 18, 13, 15],
        [ 9, 13,  8, 17,  9],
        [ 9, 14, 19,  0, 11],
        [ 0, 18,  8, 12, 10]]])

### Indexing

In [5]:
#indexing numpy arrays:
x[0]

array([[ 8, 15, 13,  8, 11],
       [18, 11,  8,  7,  2],
       [17, 11, 15,  5,  7],
       [ 3,  6,  4, 10, 11]])

In [6]:
x[2,3]

array([ 0, 18,  8, 12, 10])

In [7]:
x[:2,:3,3] #we can also subset using : operator

array([[ 8,  7,  5],
       [10, 14, 14]])

note that in lists, slicing are returned as copies, in np arrays they are returned as views, meaning if you change the view, you will change the original

In [8]:
#Reshaping

x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
x.reshape(3,3)

#sizes of the resultant reshaped must be equal to the original size

ValueError: total size of new array must be unchanged

## Computation on NP: uFuncs
"vectorized operations" i.e. operates on ndarrays in an element by element fashion

In [13]:
#Array Arithmetic:
x = np.arange(4)

print("x      =", x)
print("x + 5  =", x + 6)
print("x - 5  =", x - 3)
print("x * 2  =", x * 3)
print("x / 2  =", x / 6)
print("x // 2 =", x // 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)



[0 1 2 3]
x      = [0 1 2 3]
x + 5  = [6 7 8 9]
x - 5  = [-3 -2 -1  0]
x * 2  = [0 3 6 9]
x / 2  = [ 0.          0.16666667  0.33333333  0.5       ]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


**Other uFuncs details are left as reading assignment**

## Aggregations

In [14]:
big_array = np.random.rand(1000000)

In [15]:
%timeit sum(big_array)
%timeit np.sum(big_array)
#try this with min, max

1 loop, best of 3: 222 ms per loop
1000 loops, best of 3: 816 µs per loop


**Difference between sum and np.sum or array.sum()?**
* **sum()**      : base sum
* **np.sum()**   : multidimensional aware
* **array.sum()**: same with np.sum

In [17]:
M = np.random.random((4,3))
print(M)

[[ 0.01537852  0.25819107  0.64787252]
 [ 0.74401047  0.7299127   0.16012055]
 [ 0.26102714  0.71512351  0.9015068 ]
 [ 0.02869442  0.93745211  0.88110714]]


In [18]:
#Defaut is sum overall
M.sum()

6.2803969481120481

In [20]:
#Wht if we want to sum per column only?
# Use Axis, along which the operation is performed
M.sum(axis = 0)
# try axis = 1

array([ 1.04911055,  2.64067939,  2.590607  ])

### Broadcasting

In [22]:
a = np.array([2,3,4])
b = np.array([1,1,1])
a+b

#recall how binary ufuncs work

array([3, 4, 5])

In [24]:
a + 7

array([ 9, 10, 11])

works like: [2,3,4] + [7,7,7]

In [25]:
#Another example:
M = np.ones((3,3))
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [26]:
M + a

array([[ 3.,  4.,  5.],
       [ 3.,  4.,  5.],
       [ 3.,  4.,  5.]])

In [27]:
#JUST ONE MORE EXAMPLe
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [28]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Why do we need this?

In [56]:
#Example compute the outer products

W = np.random.random((1,10))
W

array([[ 0.99575955,  0.39169605,  0.71378415,  0.77937843,  0.93771071,
         0.19684512,  0.82824373,  0.94376192,  0.82910862,  0.95664359]])

In [59]:

X = np.random.random((30,10))


In [58]:
W*X

array([[ 0.04468023,  0.20597675,  0.48954226,  0.24225575,  0.88554419,
         0.08493625,  0.51177658,  0.42365053,  0.76147094,  0.44729902],
       [ 0.31815809,  0.36207095,  0.29879118,  0.52016328,  0.34729372,
         0.03965129,  0.78863328,  0.00300759,  0.22027434,  0.9098217 ],
       [ 0.53200728,  0.37689974,  0.29880184,  0.27888596,  0.03451492,
         0.03852004,  0.74948119,  0.73950039,  0.61234009,  0.04070959],
       [ 0.04011316,  0.13172828,  0.51206777,  0.24680612,  0.44413778,
         0.00549185,  0.00710668,  0.66564736,  0.54545233,  0.20229007],
       [ 0.83122759,  0.01514711,  0.2492483 ,  0.60341287,  0.04099385,
         0.0771441 ,  0.21962069,  0.31840106,  0.3116259 ,  0.00668343],
       [ 0.54424869,  0.23199919,  0.58557884,  0.160302  ,  0.07518009,
         0.00806352,  0.25889221,  0.61246643,  0.48092518,  0.23773897],
       [ 0.80084005,  0.12412994,  0.55453771,  0.37963582,  0.10566343,
         0.16914216,  0.35066727,  0.27743871

# Pandas
A powerful Data Analysis library for python

In [1]:
import pandas as pd

#set path to read data from
path = r'G:/GSSC/Analytics/AO GSSC/Rimar/PythonCourse'
#CrashStats

In [2]:
accident = pd.read_csv(path+'/ACCIDENT_EVENT.csv')

In [3]:
accident.head()

ACCIDENT_NO  EVENT_SEQ_NO EVENT_TYPE    Event Type Desc VEHICLE_1_ID  \
0  T20060000010             1          C          Collision            B   
1  T20060000018             1          C          Collision            B   
2  T20060000022             1          2  Fell from vehicle            A   
3  T20060000023             1          C          Collision            A   
4  T20060000026             1          C          Collision            A   

  VEHICLE_1_COLL_PT       Vehicle 1 Coll Pt Desc VEHICLE_2_ID  \
0                 2        Right side (forwards)            A   
1                 F                        Front            A   
2                 9  Not known or Not Applicable                
3                 F                        Front            B   
4                 9  Not known or Not Applicable            B   

  VEHICLE_2_COLL_PT       Vehicle 2 Coll Pt Desc PERSON_ID  OBJECT_TYPE  \
0                 F                        Front                     99   
1                 9  Not known or Not Applicable                     99   
2                                                       01           99   
3                 R                         Rear                     99   
4                 9  Not known or Not Applicable                     99   

  Object Type Desc  
0   Not Applicable  
1   Not Applicable  
2   Not Applicable  
3   Not Applicable  
4   Not Applicable

In [4]:
accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238245 entries, 0 to 238244
Data columns (total 13 columns):
ACCIDENT_NO               238245 non-null object
EVENT_SEQ_NO              238245 non-null int64
EVENT_TYPE                238245 non-null object
Event Type Desc           238245 non-null object
VEHICLE_1_ID              238245 non-null object
VEHICLE_1_COLL_PT         238245 non-null object
Vehicle 1 Coll Pt Desc    238245 non-null object
VEHICLE_2_ID              238245 non-null object
VEHICLE_2_COLL_PT         238245 non-null object
Vehicle 2 Coll Pt Desc    238245 non-null object
PERSON_ID                 238245 non-null object
OBJECT_TYPE               238245 non-null int64
Object Type Desc          238245 non-null object
dtypes: int64(2), object(11)
memory usage: 23.6+ MB


In [5]:
accident.columns

Index(['ACCIDENT_NO', 'EVENT_SEQ_NO', 'EVENT_TYPE', 'Event Type Desc',
       'VEHICLE_1_ID', 'VEHICLE_1_COLL_PT', 'Vehicle 1 Coll Pt Desc',
       'VEHICLE_2_ID', 'VEHICLE_2_COLL_PT', 'Vehicle 2 Coll Pt Desc',
       'PERSON_ID', 'OBJECT_TYPE', 'Object Type Desc'],
      dtype='object')

In [6]:
#indexing DataFrame
accident[['ACCIDENT_NO', 'EVENT_TYPE']].head()

ACCIDENT_NO EVENT_TYPE
0  T20060000010          C
1  T20060000018          C
2  T20060000022          2
3  T20060000023          C
4  T20060000026          C

In [7]:

(accident.groupby(['EVENT_TYPE'])['EVENT_TYPE'].count())

EVENT_TYPE
1     12759
2     27169
3     33266
4        57
5       392
6       300
8       844
9        26
C    163432
Name: EVENT_TYPE, dtype: int64

### Pandas Objects: Series / DataFrame / Index
Pandas objects are specialized Numpy Arrays, i.e. instead of integer indices, they used labels for indices

#### SERIES
* 1-Dimensional array of indexed data
* Generalized Numpy Array
* Specialized Dicts

In [97]:
#Let's Construct a series from a list:
S = pd.Series([x**3 for x in range(1,10)],  dtype = 'float64')
S

#Notice that the output has indexes!

0      1.0
1      8.0
2     27.0
3     64.0
4    125.0
5    216.0
6    343.0
7    512.0
8    729.0
dtype: float64

Notice that the values are just numpy arrays:

In [102]:
print(S.index)
S.values

RangeIndex(start=0, stop=9, step=1)


array([   1.,    8.,   27.,   64.,  125.,  216.,  343.,  512.,  729.])

In [105]:
#We can also index it like numpy Arrays!
S[0:3]

0     1.0
1     8.0
2    27.0
dtype: float64

**In pandas series, indices is not limited to integers!**

it can work like a dictionary

In [107]:
ex = pd.Series([.15, .30, .12, .48],
              index = ['a','b','c', 'a'])
ex

a    0.15
b    0.30
c    0.12
a    0.48
dtype: float64

In [109]:
ex['a']

a    0.15
a    0.48
dtype: float64

In [2]:
sales_dict = {'Cebu': 38332,
              'Makati': 26448,
              'BGC': 19651,
              'QC': 19552,
              'Alabang': 12882}
sales = pd.Series(sales_dict)

In [3]:
sales

Alabang    12882
BGC        19651
Cebu       38332
Makati     26448
QC         19552
dtype: int64

* dict : Series
* Keys : Index
* values : values
* arbitrary : typed

**How do we construct Series?**
> pd.Series(data, index = index)

#### DATAFRAME
* Generalization of a numpy array
* Specialization of python dicts
* two-dimensional series

Different Methods of creating a Data Frame:
* from a single series object
* from a list of dicts
* from a dict of series
* from a 2D Numpy Array
* from a Numpy structured array

**In this sessions we will focus on using Pandas for data manipulation**

https://www.rittmanmead.com/blog/2016/12/python-for-analytics-exploring-data-with-pandas/
http://blog.kaggle.com/2013/01/17/getting-started-with-pandas-predicting-sat-scores-for-new-york-city-schools/
https://medium.com/@joaoandre/introduction-to-data-science-with-pandas-b586f0257bab
pandas cook book

http://manishamde.github.io/blog/2013/03/07/pandas-and-python-top-10/

**Predicting SAT Scores for New York City Schools**

by Chris Clark

* Reading Data
* Viewing data
* Indexing
* Masking
* inserting new columns
* Summary statistics
* Variable Imputation