## Welcome to Python!!
a knowledge sharing session

The Purpose of this tutorial is to walkthrough different useful functionalities of python as a programming language for data analysis tasks. This is not a comprehensive tutorial but I hope it can deliver new items for our toolbox.



references:
* https://github.com/jakevdp/PythonDataScienceHandbook
* http://tdc-www.harvard.edu/Python.pdf
* http://pandas.pydata.org/pandas-docs/stable/10min.html
* http://twiecki.github.io/blog/2014/11/18/python-for-data-science/
* https://www.dataquest.io/blog/machine-learning-python/
* https://docs.python.org
* with additional insights from various learning experiences


## Course Outline

* Installation
* Navigating the notebook
    * importing libraries
    * getting help
    * SYNTAX - the indentation, code structure
    * data types & basic operations
    * logical Operators
    * variable assignment
    > possible break here
    * Basic data structures - List, Dicts, Tuples, Strings
    * Basic lambda functions
    * saving notebook into a script file
    
* Data Manipulation with Pandas
    * Introduction to numpy arrays
    * broadcasting, reshaping
    * operations on np arrays
    * Introduction to pandas
    * getting and reading data
    * writing data
    * DataFrame manipulation 
        * https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf
        * creating DataFrame
        * subsetting DataFrame (Masking, iloc, loc)
        * summarizing data (df.describe,np.sum(), df.head etc)
        * adding columns to DataFrame (assign, df method)
    * Merging DataFrames
    
* Introduction to Statistical Analysis and Machine Learning
    * correlation
    * Statistical tests
    * Linear regression
    * Intro to scikit functions
    
* Assignment
    











### Importing libraries
in python, we import libraries using the following commands

In [1]:
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd

In [1]:
#this is how we comment
#below is how we find help
pd?
#help(pd.DataFrame)


Object `pd` not found.


### Basic python syntax
* Indentation instead of traditional {curly_braces} 
* Use \ when we should go the next line prematurely
* in function and class definitions, a colon usually appears
* index begins in zero

In [2]:
x = [1,2,3,4,5] #example of a list
y = [1,1,1,1,1]
z = []

for i in range(0,len(x)):
    z.append(x[i]+y[i])
    print(z[i],'index: %.i' %i)



2 index: 0
3 index: 1
4 index: 2
5 index: 3
6 index: 4


In [3]:
def adder(x,y):
    """ This a docstring for
    this adder function"""
    z = [] #initialize z
    for i in range(0,len(x)):
        z.append(x[i]+y[i])
        print(z)    
    return z
    
adder(x,y)
        

[2]
[2, 3]
[2, 3, 4]
[2, 3, 4, 5]
[2, 3, 4, 5, 6]


[2, 3, 4, 5, 6]

### Data types & basic operations


In [4]:
#integers
z = int(5/2)
print(z, type(z))

#float
pi = 3.141516
print(pi, type(pi))

txt = 'This is a string' #alternatively we can use ""
print(txt, type(txt))

#Complex Number
cmp = complex(3,7)
print(cmp, type(cmp))

2 <class 'int'>
3.141516 <class 'float'>
This is a string <class 'str'>
(3+7j) <class 'complex'>


In [5]:
a = 2+3 #addition
b = 3*5 #multiplication
c = 121/7 #division
d = 7%3 #modulo


In [6]:
for i in [a,b,c,d]:
    print(i)




5
15
17.285714285714285
1


### Logical Operators
familiar logical operators are used in python

In [7]:
x = 5
y = 17
z = 9

In [8]:
print(x > y) #greater than 
print(y < 5) #less than
print(z == 9) #equal to, note the difference between variable assignment(=) and Logical operator(==)
print(y != z) #Not equal to 

False
False
True
True


In [9]:
(x < 8) or (y != 17) 

True

In [10]:
(x != 5) and (z > 9)

False

In [11]:
not( (x != 5) and (z > 9) )
#not gives the opposite

True

In [27]:
(x != 5) not (z > 9)

SyntaxError: invalid syntax (<ipython-input-27-7dfb3d79348d>, line 1)

### Variable Assignment
* In python, variable assignment create references not copies

In [83]:
x = 4 #assign 4 to x
y = x #assing x to y

In [87]:
x = 3 #change x to 3
y #print y

#note that y is changed too, y = x  did not create a copy of x to be assigned to y
#but why? :)
#try to search about Garbage collection

3

In [88]:
# we can also do multiple assignments
x,y = 'this is x', 4
print(x)
print(y)

this is x
4


## Basic Data Structures
Lists, strings and tuples are ordered sequences of objects. Unlike strings that contain only characters, list and tuples can contain any type of objects. Lists and tuples are like arrays. Tuples like strings are immutables. Lists are mutables so they can be extended or reduced at will.


### LISTS
* ordered sequence
* mutable
* can contain any type of objects

In [12]:
smpl = [1,2,3,4,5,6,7,8,91]
smpl
#Lists are defined by square brackets
#lists are mutable

[1, 2, 3, 4, 5, 6, 7, 8, 91]

In [94]:
smpl.pop(2) #here we pop the element at index 2, we can update a list!
smpl

[1, 2, 4, 5, 6, 7, 8, 91]

In [97]:
random = ['name', 100, True] #Lists can contain different types of object
random


['name', 100, True]

Problem 1: create a list of squared integers from 1 to 100

In [112]:

# sample of a list comprehension
#

#squared = [i**2 for i in range(0,100)]
#squared

### TUPLES
* ordered sequence
* immutable
* can contain any type of objects

In [98]:
tupl = (1,2,3,4,5)
tupl

(1, 2, 3, 4, 5)

In [99]:
tupl.pop(3) #this will generate an error, since you cannot modify a tuple!

AttributeError: 'tuple' object has no attribute 'pop'

### STRINGS
* strings can be thought of as a list
* but they are immutable!

In [14]:
st = "Hello QBE!"
st[8]

'E'

In [15]:
for i in st:
    print(i)

H
e
l
l
o
 
Q
B
E
!


How to know what is the type of a data?

In [16]:
d1 = 'String'
d2 = 34
d3 = [1,2,3,4]
d4 = (a,b,c,d)

In [18]:
for i in [d1,d2,d3,d4]:
    print(type(i))

<class 'str'>
<class 'int'>
<class 'list'>
<class 'tuple'>


### DICTS
dictionaries are set of key-value pairs, i.e a mapping
* objects of different types are ok
* keys : any immutable type
* values: anything
* items are key-value pairs
* defined by {curly braces}
* indexed by keys

In [168]:
d = {'tp1': 100, 'tp2': 200, 'tp3': 500, 'QBE': 4500}
d

{'QBE': 4500, 'tp1': 100, 'tp2': 200, 'tp3': 500}

**How can we build a dictionary mapping?**

In [177]:
person = ('A', 'B', 'C', 'D', 'E')
password = ('1234' , 'erZe', 'afsd', '1wh32')

In [185]:
my_dict = {} #initialize dict
for k,v in zip(person,password):
    my_dict[k] = v

#zip function returns a tuple of the passed aruments and makes them into one set

In [186]:
my_dict
#what do you notice

{'A': '1234', 'B': 'erZe', 'C': 'afsd', 'D': '1wh32'}

In [189]:
#notice that the values are printed in no particular order
my_dict.keys()



dict_keys(['C', 'A', 'B', 'D'])

In [190]:
my_dict.values()

dict_values(['afsd', '1234', 'erZe', '1wh32'])

In [191]:
my_dict.items()

dict_items([('C', 'afsd'), ('A', '1234'), ('B', 'erZe'), ('D', '1wh32')])

In [20]:
#Indexing dicts
#dicts are indexed with keys
my_dict['F']


NameError: name 'my_dict' is not defined

### Indexing and Slicing
most of the time we need to index/filter our data

In [21]:
t = ["abc", 1 , np.exp(1), [100,8,4]]



Problem: How do we get the value 8?

In [27]:
# indexing by array notation
t[0]

'abc'

In [130]:
# try negative!
t[-1]

#what's the difference?

[100, 8, 4]

In [124]:
#from index 1 up to before index 4
t[1:4]

[1, 2.7182818284590451, [100, 8, 4]]

In [28]:
range?

In [138]:
#indexing by [start:stop:step]
#start:inclusive , stop:exclusive
num = [x for x in range(1,21)]
num

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [146]:
index1 = num[0:18:3]
index1


[1, 4, 7, 10, 13, 16]

**Question how can we reverse this list?**

### The in, +,* operators

In [29]:
a_list = [i**3 for i in range(0,100)]


above is a sample of List Comprehension

In [30]:
# in
#Say for example, we want to check if an element is in a list

729 in a_list

True

In [31]:
# +
#the + operatrs for lists is for concatenation
zoo = ['tiger', 'rooster', 'pig']
add_animal = ['snake', 'kangaroo']
current = zoo + add_animal


In [32]:
# *
#the * repeats the original content
"--Hello Manila "*3

'--Hello Manila --Hello Manila --Hello Manila '

## APPEND / POP
**What if we want to replace a contents of a list?**

In [33]:
current

['tiger', 'rooster', 'pig', 'snake', 'kangaroo']

In [34]:
current[1] = 'monkey'
#here we assigned the element to 'monkey'

In [35]:
current

['tiger', 'monkey', 'pig', 'snake', 'kangaroo']

**I want to add catterpillar, how can I do it?**

In [36]:
current.append('catterpillar')
current

['tiger', 'monkey', 'pig', 'snake', 'kangaroo', 'catterpillar']

**I want to remove the snake**

In [40]:
# snake is in index 3
current.pop(3)
current

['tiger', 'monkey', 'pig', 'kangaroo', 'catterpillar']

### Defining a function with an if-else statement

In [59]:
def is_larger(x,num):
    if x > num:
        print('your fave number ' + x + ' is larger than ' +num)
    elif x < num:
        print('uhhhm this is lesser than your favorite', x)
    else:
        print('Just equal')

In [60]:
x = input("enter your favorite number: ")
num = input("Enter a random number: ")
is_larger(x,num)

enter your favorite number: 23
Enter a random number: 11
your fave number 23 is larger than 11


**Now we want to save this file as .ipynb format**

## Numpy Arrays
building blocks of Pandas and some more advanced libraries like tensorflow

**So what's a numpy array?**

Cotains values of a single type,

to see full list of available dtypes see: http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb


In [1]:
import numpy as np

n = np.array([12,3,4,5,6,7,8], dtype = 'float64')
n

#similar to a list

array([ 12.,   3.,   4.,   5.,   6.,   7.,   8.])

In [2]:
n.dtype

dtype('float64')

In [3]:
#numpy arrays can also be multidimensional arrays
np.random.seed(2)

x = np.random.randint(20, size = (3,4,5))
print(x.shape) #.ndim, .size
x

(3, 4, 5)


array([[[ 8, 15, 13,  8, 11],
        [18, 11,  8,  7,  2],
        [17, 11, 15,  5,  7],
        [ 3,  6,  4, 10, 11]],

       [[19,  7,  6, 10,  1],
        [ 3,  5,  4, 14,  6],
        [19,  2, 16, 14, 12],
        [18,  4, 15, 17,  7]],

       [[14,  8, 18, 13, 15],
        [ 9, 13,  8, 17,  9],
        [ 9, 14, 19,  0, 11],
        [ 0, 18,  8, 12, 10]]])

### Slicing and Indexing

In [4]:
#indexing numpy arrays:
x[0]

array([[ 8, 15, 13,  8, 11],
       [18, 11,  8,  7,  2],
       [17, 11, 15,  5,  7],
       [ 3,  6,  4, 10, 11]])

In [5]:
x[2,3]

array([ 0, 18,  8, 12, 10])

In [6]:
x[:2,:3,3] #we can also subset using : operator

array([[ 8,  7,  5],
       [10, 14, 14]])

In [7]:
#Reshaping

x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x.reshape(3,3)

#sizes of the resultant reshaped must be equal to the original size

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Computation on NP: uFuncs
"vectorized operations" i.e. operates on ndarrays in an element by element fashion

In [9]:
#Array Arithmetic:
x = np.arange(4)

print("x      =", x)
print("x + 5  =", x + 6)
print("x - 5  =", x - 3)
print("x * 2  =", x * 3)
print("x / 2  =", x / 6)
print("x // 2 =", x // 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)



x      = [0 1 2 3]
x + 5  = [6 7 8 9]
x - 5  = [-3 -2 -1  0]
x * 2  = [0 3 6 9]
x / 2  = [ 0.          0.16666667  0.33333333  0.5       ]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [16]:
#Let's try to compute outer products:
product_ratings = [2,1,5,3,2,4]
user_ratings = [3,2,5,4,6,1]

np.multiply.outer(product_ratings, user_ratings)



array([[ 6,  4, 10,  8, 12,  2],
       [ 3,  2,  5,  4,  6,  1],
       [15, 10, 25, 20, 30,  5],
       [ 9,  6, 15, 12, 18,  3],
       [ 6,  4, 10,  8, 12,  2],
       [12,  8, 20, 16, 24,  4]])

Other uFunc details are left as reading assignment

## Aggregations

In [12]:
big_array = np.random.rand(10)

**Difference between sum and np.sum or array.sum()?**
* **sum()**      : element wise sum
* **np.sum()**   : multiple array dimensions aware. Returns aggregate over an entire array by default
* **array.sum()**: same with np.sum

In [13]:
%timeit sum(big_array,big_array)
%timeit np.sum(big_array)
%timeit big_array.sum()
#try this with min, max

The slowest run took 4.72 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 18.2 µs per loop
The slowest run took 6.95 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.39 µs per loop
The slowest run took 4.04 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.61 µs per loop


In [17]:
print(sum(big_array,big_array))
print(np.sum(big_array))
print(big_array.sum())

[ 6.1564934   5.58557567  6.06541239  5.80031579  5.4681232   5.91216973
  5.88728242  6.27662392  5.95490695  6.23496395]
5.39471522092
5.39471522092


In [17]:
M = np.random.random((4,3))
print(M)

[[ 0.01537852  0.25819107  0.64787252]
 [ 0.74401047  0.7299127   0.16012055]
 [ 0.26102714  0.71512351  0.9015068 ]
 [ 0.02869442  0.93745211  0.88110714]]


In [18]:
#Defaut is sum overall
M.sum()

6.2803969481120481

In [20]:
#Wht if we want to sum per column only?
# Use Axis, along which the operation is performed
M.sum(axis = 0)
# try axis = 1

array([ 1.04911055,  2.64067939,  2.590607  ])

### Broadcasting

In [22]:
a = np.array([2,3,4])
b = np.array([1,1,1])
a+b

#recall how binary ufuncs work

array([3, 4, 5])

In [24]:
a + 7

array([ 9, 10, 11])

works like: [2,3,4] + [7,7,7]

In [25]:
#Another example:
M = np.ones((3,3))
M

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [26]:
M + a

array([[ 3.,  4.,  5.],
       [ 3.,  4.,  5.],
       [ 3.,  4.,  5.]])

In [27]:
#JUST ONE MORE EXAMPLe
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [28]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Sorting Arrays

In [20]:
n = np.array([1,3,2,5,3,9,1])

In [21]:
np.sort(n)

array([1, 1, 2, 3, 3, 5, 9])

In [24]:
n.sort()
print(n)

[1 1 2 3 3 5 9]


argsort returns idices of arrays instead of the actual elements

In [25]:
n = np.array([1,3,2,5,3,9,1])
np.argsort(n)

array([0, 6, 2, 1, 4, 3, 5], dtype=int64)

you may visit http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.08-Sorting.ipynb for an application of sorting to KNN algorithm

### Pandas Objects: Series / DataFrame / Index
Pandas objects are specialized Numpy Arrays, i.e. instead of integer indices, they used labels for indices

#### SERIES
* 1-Dimensional array of indexed data
* Generalized Numpy Array
* Specialized Dicts

In [97]:
#Let's Construct a series from a list:
S = pd.Series([x**3 for x in range(1,10)],  dtype = 'float64')
S

#Notice that the output has indexes!

0      1.0
1      8.0
2     27.0
3     64.0
4    125.0
5    216.0
6    343.0
7    512.0
8    729.0
dtype: float64

Notice that the values are just numpy arrays:

In [102]:
print(S.index)
S.values

RangeIndex(start=0, stop=9, step=1)


array([   1.,    8.,   27.,   64.,  125.,  216.,  343.,  512.,  729.])

In [105]:
#We can also index it like numpy Arrays!
S[0:3]

0     1.0
1     8.0
2    27.0
dtype: float64

**In pandas series, indices is not limited to integers!**

it can work like a dictionary

In [107]:
ex = pd.Series([.15, .30, .12, .48],
              index = ['a','b','c', 'a'])
ex

a    0.15
b    0.30
c    0.12
a    0.48
dtype: float64

In [109]:
ex['a']

a    0.15
a    0.48
dtype: float64

In [2]:
sales_dict = {'Cebu': 38332,
              'Makati': 26448,
              'BGC': 19651,
              'QC': 19552,
              'Alabang': 12882}
sales = pd.Series(sales_dict)

In [3]:
sales

Alabang    12882
BGC        19651
Cebu       38332
Makati     26448
QC         19552
dtype: int64

* dict : Series
* Keys : Index
* values : values
* arbitrary : typed

**How do we construct Series?**
> pd.Series(data, index = index)

#### DATAFRAME
* Generalization of a numpy array
* Specialization of python dicts
* two-dimensional series